@startuml

title __OSE's Class Diagram__\n

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.ose {
          class cardfilesystem.egk2mf.df.hca.df.ose.Ef {
              {static} + OSE : Ose
              {static} + StatusOse : StatusOse
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.ose {
          class cardfilesystem.egk2mf.df.hca.df.ose.Ef.Ose {
              {static} + FID : int
              {static} + SFID : int
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.ose {
          class cardfilesystem.egk2mf.df.hca.df.ose.Ef.StatusOse {
              {static} + FID : int
              {static} + SFID : int
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.ose {
          class cardfilesystem.egk2mf.df.hca.df.ose.MrPin {
              {static} + OSE : Ose
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.ose {
          class cardfilesystem.egk2mf.df.hca.df.ose.MrPin.Ose {
              {static} + PW : int
          }
        }
      }
    }
  }
  

  cardfilesystem.egk2mf.df.hca.df.ose.Ef +-down- cardfilesystem.egk2mf.df.hca.df.ose.Ef.Ose
  cardfilesystem.egk2mf.df.hca.df.ose.Ef +-down- cardfilesystem.egk2mf.df.hca.df.ose.Ef.StatusOse
  cardfilesystem.egk2mf.df.hca.df.ose.MrPin +-down- cardfilesystem.egk2mf.df.hca.df.ose.MrPin.Ose


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
