@startuml

title __AUTO's Class Diagram__\n

  namespace cardfilesystem {
    namespace hba21mf {
      namespace df.auto {
        class cardfilesystem.hba21mf.df.auto.Ef {
            {static} + C_HP_AUTO1_R3072 : ChpAuto1R3072
            {static} + C_HP_AUTO2_R3072 : ChpAuto2R3072
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba21mf {
      namespace df.auto {
        class cardfilesystem.hba21mf.df.auto.Ef.ChpAuto1R3072 {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba21mf {
      namespace df.auto {
        class cardfilesystem.hba21mf.df.auto.Ef.ChpAuto2R3072 {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba21mf {
      namespace df.auto {
        class cardfilesystem.hba21mf.df.auto.Pin {
            {static} + AUTO : Auto
            {static} + SO : So
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba21mf {
      namespace df.auto {
        class cardfilesystem.hba21mf.df.auto.Pin.Auto {
            {static} + PWID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba21mf {
      namespace df.auto {
        class cardfilesystem.hba21mf.df.auto.Pin.So {
            {static} + PWID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba21mf {
      namespace df.auto {
        class cardfilesystem.hba21mf.df.auto.PrK {
            {static} + HP_AUTO_R3072 : HpAutoR3072
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba21mf {
      namespace df.auto {
        class cardfilesystem.hba21mf.df.auto.PrK.HpAutoR3072 {
            {static} + KID : int
        }
      }
    }
  }
  

  cardfilesystem.hba21mf.df.auto.Ef +-down- cardfilesystem.hba21mf.df.auto.Ef.ChpAuto1R3072
  cardfilesystem.hba21mf.df.auto.Ef +-down- cardfilesystem.hba21mf.df.auto.Ef.ChpAuto2R3072
  cardfilesystem.hba21mf.df.auto.Pin +-down- cardfilesystem.hba21mf.df.auto.Pin.Auto
  cardfilesystem.hba21mf.df.auto.Pin +-down- cardfilesystem.hba21mf.df.auto.Pin.So
  cardfilesystem.hba21mf.df.auto.PrK +-down- cardfilesystem.hba21mf.df.auto.PrK.HpAutoR3072


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
