@startuml

title __AMTS's Class Diagram__\n

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.amts {
          class cardfilesystem.egk2mf.df.hca.df.amts.Ef {
              {static} + AMTS : Amts
              {static} + EinwilligungsAMTS : EinwilligungAmts
              {static} + StatusAMTS : StatusAmts
              {static} + VerweiseAMTS : VersweiseAmts
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.amts {
          class cardfilesystem.egk2mf.df.hca.df.amts.Ef.Amts {
              {static} + FID : int
              {static} + SFID : int
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.amts {
          class cardfilesystem.egk2mf.df.hca.df.amts.Ef.EinwilligungAmts {
              {static} + FID : int
              {static} + SFID : int
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.amts {
          class cardfilesystem.egk2mf.df.hca.df.amts.Ef.StatusAmts {
              {static} + FID : int
              {static} + SFID : int
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.amts {
          class cardfilesystem.egk2mf.df.hca.df.amts.Ef.VersweiseAmts {
              {static} + FID : int
              {static} + SFID : int
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.amts {
          class cardfilesystem.egk2mf.df.hca.df.amts.MrPin {
              {static} + AMTS : Amts
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.amts {
          class cardfilesystem.egk2mf.df.hca.df.amts.MrPin.Amts {
              {static} + PWID : int
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.amts {
          class cardfilesystem.egk2mf.df.hca.df.amts.Pin {
              {static} + AMTS_REP : AmtsRep
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.amts {
          class cardfilesystem.egk2mf.df.hca.df.amts.Pin.AmtsRep {
              {static} + PWID : int
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.amts {
          class cardfilesystem.egk2mf.df.hca.df.amts.PrK {
              {static} + AMTS_ENC_E256 : AmtsEncE256
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.amts {
          class cardfilesystem.egk2mf.df.hca.df.amts.PrK.AmtsEncE256 {
              {static} + PWID : int
          }
        }
      }
    }
  }
  

  cardfilesystem.egk2mf.df.hca.df.amts.Ef +-down- cardfilesystem.egk2mf.df.hca.df.amts.Ef.Amts
  cardfilesystem.egk2mf.df.hca.df.amts.Ef +-down- cardfilesystem.egk2mf.df.hca.df.amts.Ef.EinwilligungAmts
  cardfilesystem.egk2mf.df.hca.df.amts.Ef +-down- cardfilesystem.egk2mf.df.hca.df.amts.Ef.StatusAmts
  cardfilesystem.egk2mf.df.hca.df.amts.Ef +-down- cardfilesystem.egk2mf.df.hca.df.amts.Ef.VersweiseAmts
  cardfilesystem.egk2mf.df.hca.df.amts.MrPin +-down- cardfilesystem.egk2mf.df.hca.df.amts.MrPin.Amts
  cardfilesystem.egk2mf.df.hca.df.amts.Pin +-down- cardfilesystem.egk2mf.df.hca.df.amts.Pin.AmtsRep
  cardfilesystem.egk2mf.df.hca.df.amts.PrK +-down- cardfilesystem.egk2mf.df.hca.df.amts.PrK.AmtsEncE256


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
