@startuml

package de.gematik.ti.healthcardaccess {
    package de.gematik.ti.healthcardaccess.cardobjects {
      interface ICardKeyReference {
          {static} + DF_SPECIFIC_PWD_MARKER : int
          {abstract} + calculateKeyReference()
      }
    }
  }

package de.gematik.ti.healthcardaccess {
    package de.gematik.ti.healthcardaccess.cardobjects {
      class Key {
          {static} - MIN_KEY_ID : int
          {static} - MAX_KEY_ID : int
          - keyId : int
          + Key()
          + getkeyId()
          - sanityCheck()
          + calculateKeyReference()
      }
    }
  }


  package de.gematik.ti.healthcardaccess {
    package de.gematik.ti.healthcardaccess.cardobjects {
      class Password {
          {static} - MIN_PWD_ID : int
          {static} - MAX_PWD_ID : int
          - pwdId : int
          + Password()
          + getPwdId()
          - sanityCheck()
          + calculateKeyReference()
      }
    }
  }

  Key -up-|> ICardKeyReference
  Password -up-|> ICardKeyReference

@enduml
