@startuml

title __QES's Class Diagram__\n

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.qes {
        class cardfilesystem.egk2mf.df.qes.Ef {
            {static} + C_CH_QES_R2048 : CchQesR2048
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.qes {
        class cardfilesystem.egk2mf.df.qes.Ef.CchQesR2048 {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.qes {
        class cardfilesystem.egk2mf.df.qes.Pin {
            {static} + QES : Qes
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.qes {
        class cardfilesystem.egk2mf.df.qes.Pin.Qes {
            {static} + PWID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.qes {
        class cardfilesystem.egk2mf.df.qes.PrK {
            {static} + CH_QES_R2048 : ChQesR2048
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.qes {
        class cardfilesystem.egk2mf.df.qes.PrK.ChQesR2048 {
            {static} + KID : int
        }
      }
    }
  }
  

  cardfilesystem.egk2mf.df.qes.Ef +-down- cardfilesystem.egk2mf.df.qes.Ef.CchQesR2048
  cardfilesystem.egk2mf.df.qes.Pin +-down- cardfilesystem.egk2mf.df.qes.Pin.Qes
  cardfilesystem.egk2mf.df.qes.PrK +-down- cardfilesystem.egk2mf.df.qes.PrK.ChQesR2048


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
