@startuml

title __ESIGN's Class Diagram__\n

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.esign {
        class cardfilesystem.egk2mf.df.esign.Ef {
            {static} + C_CH_AUTN_R2048 : CchAutnR2048
            {static} + C_CH_AUT_R2048 : CchAutR2048
            {static} + C_CH_ENCV_R2048 : CchEncvR2048
            {static} + C_CH_ENC_R2048 : CchEncR2048
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.esign {
        class cardfilesystem.egk2mf.df.esign.Ef.CchAutR2048 {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.esign {
        class cardfilesystem.egk2mf.df.esign.Ef.CchAutnR2048 {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.esign {
        class cardfilesystem.egk2mf.df.esign.Ef.CchEncR2048 {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.esign {
        class cardfilesystem.egk2mf.df.esign.Ef.CchEncvR2048 {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.esign {
        class cardfilesystem.egk2mf.df.esign.PrK {
            {static} + CH_AUTN_R2048 : ChAutnR2048
            {static} + CH_AUT_R2048 : ChAutR2048
            {static} + CH_ENCV_R2048 : ChEncvR2048
            {static} + CH_ENC_R2048 : ChEncR2048
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.esign {
        class cardfilesystem.egk2mf.df.esign.PrK.ChAutR2048 {
            {static} + KID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.esign {
        class cardfilesystem.egk2mf.df.esign.PrK.ChAutnR2048 {
            {static} + KID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.esign {
        class cardfilesystem.egk2mf.df.esign.PrK.ChEncR2048 {
            {static} + KID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.esign {
        class cardfilesystem.egk2mf.df.esign.PrK.ChEncvR2048 {
            {static} + KID : int
        }
      }
    }
  }
  

  cardfilesystem.egk2mf.df.esign.Ef +-down- cardfilesystem.egk2mf.df.esign.Ef.CchAutR2048
  cardfilesystem.egk2mf.df.esign.Ef +-down- cardfilesystem.egk2mf.df.esign.Ef.CchAutnR2048
  cardfilesystem.egk2mf.df.esign.Ef +-down- cardfilesystem.egk2mf.df.esign.Ef.CchEncR2048
  cardfilesystem.egk2mf.df.esign.Ef +-down- cardfilesystem.egk2mf.df.esign.Ef.CchEncvR2048
  cardfilesystem.egk2mf.df.esign.PrK +-down- cardfilesystem.egk2mf.df.esign.PrK.ChAutR2048
  cardfilesystem.egk2mf.df.esign.PrK +-down- cardfilesystem.egk2mf.df.esign.PrK.ChAutnR2048
  cardfilesystem.egk2mf.df.esign.PrK +-down- cardfilesystem.egk2mf.df.esign.PrK.ChEncR2048
  cardfilesystem.egk2mf.df.esign.PrK +-down- cardfilesystem.egk2mf.df.esign.PrK.ChEncvR2048


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
