@startuml



  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.auto {
        class cardfilesystem.hba2mf.df.auto.Ef {
            {static} + C_HP_AUTO1_R2048 : ChpAuto1R2048
            {static} + C_HP_AUTO2_R2048 : ChpAuto2R2048
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.auto {
        class cardfilesystem.hba2mf.df.auto.Ef.ChpAuto1R2048 {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.auto {
        class cardfilesystem.hba2mf.df.auto.Ef.ChpAuto2R2048 {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.auto {
        class cardfilesystem.hba2mf.df.auto.Pin {
            {static} + AUTO : Auto
            {static} + SO : So
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.auto {
        class cardfilesystem.hba2mf.df.auto.Pin.Auto {
            {static} + PWID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.auto {
        class cardfilesystem.hba2mf.df.auto.Pin.So {
            {static} + PWID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.auto {
        class cardfilesystem.hba2mf.df.auto.PrK {
            {static} + HP_AUTO_R2048 : HpAutoR2048
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.auto {
        class cardfilesystem.hba2mf.df.auto.PrK.HpAutoR2048 {
            {static} + KID : int
        }
      }
    }
  }
  

  cardfilesystem.hba2mf.df.auto.Ef +-down- cardfilesystem.hba2mf.df.auto.Ef.ChpAuto1R2048
  cardfilesystem.hba2mf.df.auto.Ef +-down- cardfilesystem.hba2mf.df.auto.Ef.ChpAuto2R2048
  cardfilesystem.hba2mf.df.auto.Pin +-down- cardfilesystem.hba2mf.df.auto.Pin.Auto
  cardfilesystem.hba2mf.df.auto.Pin +-down- cardfilesystem.hba2mf.df.auto.Pin.So
  cardfilesystem.hba2mf.df.auto.PrK +-down- cardfilesystem.hba2mf.df.auto.PrK.HpAutoR2048









@enduml
