@startuml



  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.ciaesign {
        class cardfilesystem.hba2mf.df.ciaesign.Ef {
            {static} + AOD : Aod
            {static} + CD : Cd
            {static} + CIA_CIAInfo : CiaCiaInfo
            {static} + OD : Od
            {static} + PrKD : PrKd
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.ciaesign {
        class cardfilesystem.hba2mf.df.ciaesign.Ef.Aod {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.ciaesign {
        class cardfilesystem.hba2mf.df.ciaesign.Ef.Cd {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.ciaesign {
        class cardfilesystem.hba2mf.df.ciaesign.Ef.CiaCiaInfo {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.ciaesign {
        class cardfilesystem.hba2mf.df.ciaesign.Ef.Od {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.ciaesign {
        class cardfilesystem.hba2mf.df.ciaesign.Ef.PrKd {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  cardfilesystem.hba2mf.df.ciaesign.Ef +-down- cardfilesystem.hba2mf.df.ciaesign.Ef.Aod
  cardfilesystem.hba2mf.df.ciaesign.Ef +-down- cardfilesystem.hba2mf.df.ciaesign.Ef.Cd
  cardfilesystem.hba2mf.df.ciaesign.Ef +-down- cardfilesystem.hba2mf.df.ciaesign.Ef.CiaCiaInfo
  cardfilesystem.hba2mf.df.ciaesign.Ef +-down- cardfilesystem.hba2mf.df.ciaesign.Ef.Od
  cardfilesystem.hba2mf.df.ciaesign.Ef +-down- cardfilesystem.hba2mf.df.ciaesign.Ef.PrKd









@enduml
