@startuml



  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Df {
          {static} + CIA_ESIGN : CiaEsign
          {static} + ESIGN : Esign
          {static} + HCA : Hca
          {static} + QES : Qes
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Df.CiaEsign {
          {static} + AID : String
          {static} + EF : Ef
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Df.Esign {
          {static} + AID : String
          {static} + EF : Ef
          {static} + PrK : PrK
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Df.Hca {
          {static} + AID : String
          {static} + DF : Df
          {static} + EF : Ef
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Df.Qes {
          {static} + AID : String
          {static} + EF : Ef
          {static} + PIN : Pin
          {static} + PrK : PrK
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Ef {
          {static} + ATR : Atr
          {static} + C_CA_EGK_CS_E256 : CcaEgkCsE256
          {static} + C_EGK_AUT_CVC_E256 : CegkAutCvcE256
          {static} + CardAccess : CardAccess
          {static} + DIR : Dir
          {static} + GDO : Gdo
          {static} + Version : Version
          {static} + Version2 : Version2
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Ef.Atr {
          {static} + FID : int
          {static} + SFID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Ef.CardAccess {
          {static} + FID : int
          {static} + SFID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Ef.CcaEgkCsE256 {
          {static} + FID : int
          {static} + SFID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Ef.CegkAutCvcE256 {
          {static} + FID : int
          {static} + SFID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Ef.Dir {
          {static} + FID : int
          {static} + SFID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Ef.Gdo {
          {static} + FID : int
          {static} + SFID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Ef.Version {
          {static} + FID : int
          {static} + SFID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Ef.Version2 {
          {static} + FID : int
          {static} + SFID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.MrPin {
          {static} + home : Home
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.MrPin.Home {
          {static} + PWID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Pin {
          {static} + CH : Ch
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Pin.Ch {
          {static} + PWID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.PrK {
          {static} + EGK_AUT_CVC_E256 : EgkAutCvcE256
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.PrK.EgkAutCvcE256 {
          {static} + KID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Sk {
          {static} + CAN : Can
          {static} + CMS_AES128 : CmsAes128
          {static} + CMS_AES256 : CmsAes256
          {static} + VSD_AES128 : VsdAes128
          {static} + VSD_AES256 : VsdAes256
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Sk.Can {
          {static} + KID : int
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Sk.CmsAes128 {
          {static} - KID : int
          + getKID()
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Sk.CmsAes256 {
          {static} - KID : int
          + getKID()
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      interface cardfilesystem.egk2mf.Sk.ICMSSymkey {
          {abstract} + getKID()
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      interface cardfilesystem.egk2mf.Sk.IVSDSymkey {
          {abstract} + getKID()
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Sk.VsdAes128 {
          {static} - KID : int
          + getKID()
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      class cardfilesystem.egk2mf.Sk.VsdAes256 {
          {static} - KID : int
          + getKID()
      }
    }
  }
  

  cardfilesystem.egk2mf.Df +-down- cardfilesystem.egk2mf.Df.CiaEsign
  cardfilesystem.egk2mf.Df +-down- cardfilesystem.egk2mf.Df.Esign
  cardfilesystem.egk2mf.Df +-down- cardfilesystem.egk2mf.Df.Hca
  cardfilesystem.egk2mf.Df +-down- cardfilesystem.egk2mf.Df.Qes
  cardfilesystem.egk2mf.Ef +-down- cardfilesystem.egk2mf.Ef.Atr
  cardfilesystem.egk2mf.Ef +-down- cardfilesystem.egk2mf.Ef.CardAccess
  cardfilesystem.egk2mf.Ef +-down- cardfilesystem.egk2mf.Ef.CcaEgkCsE256
  cardfilesystem.egk2mf.Ef +-down- cardfilesystem.egk2mf.Ef.CegkAutCvcE256
  cardfilesystem.egk2mf.Ef +-down- cardfilesystem.egk2mf.Ef.Dir
  cardfilesystem.egk2mf.Ef +-down- cardfilesystem.egk2mf.Ef.Gdo
  cardfilesystem.egk2mf.Ef +-down- cardfilesystem.egk2mf.Ef.Version
  cardfilesystem.egk2mf.Ef +-down- cardfilesystem.egk2mf.Ef.Version2
  cardfilesystem.egk2mf.MrPin +-down- cardfilesystem.egk2mf.MrPin.Home
  cardfilesystem.egk2mf.Pin +-down- cardfilesystem.egk2mf.Pin.Ch
  cardfilesystem.egk2mf.PrK +-down- cardfilesystem.egk2mf.PrK.EgkAutCvcE256
  cardfilesystem.egk2mf.Sk +-down- cardfilesystem.egk2mf.Sk.Can
  cardfilesystem.egk2mf.Sk +-down- cardfilesystem.egk2mf.Sk.CmsAes128
  cardfilesystem.egk2mf.Sk +-down- cardfilesystem.egk2mf.Sk.CmsAes256
  cardfilesystem.egk2mf.Sk +-down- cardfilesystem.egk2mf.Sk.ICMSSymkey
  cardfilesystem.egk2mf.Sk +-down- cardfilesystem.egk2mf.Sk.IVSDSymkey
  cardfilesystem.egk2mf.Sk +-down- cardfilesystem.egk2mf.Sk.VsdAes128
  cardfilesystem.egk2mf.Sk +-down- cardfilesystem.egk2mf.Sk.VsdAes256
  cardfilesystem.egk2mf.Sk.CmsAes128 .up.|> cardfilesystem.egk2mf.Sk.ICMSSymkey
  cardfilesystem.egk2mf.Sk.CmsAes256 .up.|> cardfilesystem.egk2mf.Sk.ICMSSymkey
  cardfilesystem.egk2mf.Sk.VsdAes128 .up.|> cardfilesystem.egk2mf.Sk.IVSDSymkey
  cardfilesystem.egk2mf.Sk.VsdAes256 .up.|> cardfilesystem.egk2mf.Sk.IVSDSymkey









@enduml
