@startuml



  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.gdd {
          class cardfilesystem.egk2mf.df.hca.df.gdd.Ef {
              {static} + EinwilligungGDD : EinwilligungGdd
              {static} + VerweiseGDD : VerweiseGdd
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.gdd {
          class cardfilesystem.egk2mf.df.hca.df.gdd.Ef.EinwilligungGdd {
              {static} + FID : int
              {static} + SFID : int
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.gdd {
          class cardfilesystem.egk2mf.df.hca.df.gdd.Ef.VerweiseGdd {
              {static} + FID : int
              {static} + SFID : int
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.gdd {
          class cardfilesystem.egk2mf.df.hca.df.gdd.MrPin {
              {static} + GDD : Gdd
          }
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace egk2mf {
      namespace df.hca {
        namespace df.gdd {
          class cardfilesystem.egk2mf.df.hca.df.gdd.MrPin.Gdd {
              {static} + PWID : int
          }
        }
      }
    }
  }
  

  cardfilesystem.egk2mf.df.hca.df.gdd.Ef +-down- cardfilesystem.egk2mf.df.hca.df.gdd.Ef.EinwilligungGdd
  cardfilesystem.egk2mf.df.hca.df.gdd.Ef +-down- cardfilesystem.egk2mf.df.hca.df.gdd.Ef.VerweiseGdd
  cardfilesystem.egk2mf.df.hca.df.gdd.MrPin +-down- cardfilesystem.egk2mf.df.hca.df.gdd.MrPin.Gdd









@enduml
