@startuml



  namespace de.gematik.ti.healthcardaccess {
    namespace healthcards {
      class de.gematik.ti.healthcardaccess.healthcards.Egk2 {
      }
    }
  }
  

  namespace de.gematik.ti.healthcardaccess {
    namespace healthcards {
      class de.gematik.ti.healthcardaccess.healthcards.Egk21 {
      }
    }
  }
  

  namespace de.gematik.ti.healthcardaccess {
    namespace healthcards {
      class de.gematik.ti.healthcardaccess.healthcards.Hba2 {
      }
    }
  }
  

  namespace de.gematik.ti.healthcardaccess {
    namespace healthcards {
      class de.gematik.ti.healthcardaccess.healthcards.Hba21 {
      }
    }
  }
  

  namespace de.gematik.ti.healthcardaccess {
    namespace healthcards {
      class de.gematik.ti.healthcardaccess.healthcards.HealthCardStatusInvalid {
          + isValid()
      }
    }
  }
  

  namespace de.gematik.ti.healthcardaccess {
    namespace healthcards {
      class de.gematik.ti.healthcardaccess.healthcards.HealthCardStatusUnknown {
          + isValid()
      }
    }
  }
  

  namespace de.gematik.ti.healthcardaccess {
    namespace healthcards {
      class de.gematik.ti.healthcardaccess.healthcards.HealthCardStatusValid {
          + HealthCardStatusValid()
          + getHealthCardType()
          + isValid()
          + setHealthCardType()
      }
    }
  }
  

  namespace de.gematik.ti.healthcardaccess {
    namespace healthcards {
      class de.gematik.ti.healthcardaccess.healthcards.Smcb2 {
      }
    }
  }
  

  namespace de.gematik.ti.healthcardaccess {
    namespace healthcards {
      class de.gematik.ti.healthcardaccess.healthcards.Smcb21 {
      }
    }
  }
  

  namespace de.gematik.ti.healthcardaccess {
    namespace healthcards {
      class de.gematik.ti.healthcardaccess.healthcards.Unknown {
      }
    }
  }
  

  de.gematik.ti.healthcardaccess.healthcards.Egk2 .up.|> de.gematik.ti.healthcardaccess.IHealthCardType
  de.gematik.ti.healthcardaccess.healthcards.Egk21 .up.|> de.gematik.ti.healthcardaccess.IHealthCardType
  de.gematik.ti.healthcardaccess.healthcards.Hba2 .up.|> de.gematik.ti.healthcardaccess.IHealthCardType
  de.gematik.ti.healthcardaccess.healthcards.Hba21 .up.|> de.gematik.ti.healthcardaccess.IHealthCardType
  de.gematik.ti.healthcardaccess.healthcards.HealthCardStatusInvalid .up.|> de.gematik.ti.healthcardaccess.IHealthCardStatus
  de.gematik.ti.healthcardaccess.healthcards.HealthCardStatusUnknown .up.|> de.gematik.ti.healthcardaccess.IHealthCardStatus
  de.gematik.ti.healthcardaccess.healthcards.HealthCardStatusValid .up.|> de.gematik.ti.healthcardaccess.IHealthCardStatus
  de.gematik.ti.healthcardaccess.healthcards.HealthCardStatusValid o-- de.gematik.ti.healthcardaccess.IHealthCardType : healthCardType
  de.gematik.ti.healthcardaccess.healthcards.Smcb2 .up.|> de.gematik.ti.healthcardaccess.IHealthCardType
  de.gematik.ti.healthcardaccess.healthcards.Smcb21 .up.|> de.gematik.ti.healthcardaccess.IHealthCardType
  de.gematik.ti.healthcardaccess.healthcards.Unknown .up.|> de.gematik.ti.healthcardaccess.IHealthCardType









@enduml
