include::config.adoc[]
== Getting Started
=== Create a command
The design of this API follows the link:https://en.wikipedia.org/wiki/Command_pattern[command design pattern]
as well as functional programming paradigm comparable to http://reactivex.io/[ReactiveX].
Thus a command object of appropriate command class for the desired command to be sent has to be created
first. When creating the command it needs to be configured to be configured.

Following example shall send a +SELECT+ command to a smartcard in order to select the folder
(aka Distinguished File = DF) +DF.HCA+. So we need to to create a SelectCommand object an pass the
FileIdentifier of +DF.HCA+ to the command object.

[source,java]
----
AbstractHealthCardCommand hcc = new SelectCommand(Egk.Df.HCA.getAid());
----

As commands are executed on smartcards, such command object can be executed on a card object.
Next example presumes that we already got an Egk object as one kind of a healthcard. The
result of command execution can be validated against an expected response status,
e.g. SUCCESS response status. In order to test the response status it needs to be
retrieved from the execution response. This is done by mapping `ResultOperation<Response>` to
`ResultOperation<ResponseStatus>` and to test it against the expected `ResponseStatus` by means of
`TestSubscriber` object created  by calling `test()` method . This is
shown in next example.

[source,java]
----
private Egk hc;
...

ResultOperation<Response> result = hcc.executeOn(hc);
ResultOperation<Response.ResponseStatus> status = result.map(Response::getResponseStatus);
TestSubscriber<Response.ResponseStatus> subscriber = status.test();
subscriber.assertValue(Response.ResponseStatus.SUCCESS);
----

If command execution returns a different value than SUCCESS as expected in example above, an
`AssertionError` is thrown at the end of command execution.

The example above can be written in a much shorter format by omitting the object references and
chaing the method executions, like shown below.

[source,java]
----
private Egk hc;
...

hcc.executeOn(hc)
                .map(Response::getResponseStatus)
                .test()
                .assertValue(Response.ResponseStatus.SUCCESS);
----

=== Build setup
To use HealthCardAccess library in a project, you need just to include following dependency:

.Gradle dependency settings to use healthcard access library
[source, groovy, subs="attributes+"]
dependencies {
    implementation group: 'de.gematik.ti', name: 'healthcard.access', version: '1.2.1'
}

.Maven dependency settings to use healthcard access library
[source, xml, subs="attributes+"]
<dependencies>
    <dependency>
        <groupId>de.gematik.ti</groupId>
        <artifactId>healthcard.acces</artifactId>
        <version>1.2.1</version>
    </dependency>
</dependencies>



