@startuml

title __ESIGN's Class Diagram__\n

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.esign {
        class cardfilesystem.hba2mf.df.esign.Ef {
            {static} + C_CH_AUT_R2048 : ChpAutR2048
            {static} + C_CH_ENC_R2048 : ChpEncR2048
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.esign {
        class cardfilesystem.hba2mf.df.esign.Ef.ChpAutR2048 {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.esign {
        class cardfilesystem.hba2mf.df.esign.Ef.ChpEncR2048 {
            {static} + FID : int
            {static} + SFID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.esign {
        class cardfilesystem.hba2mf.df.esign.PrK {
            {static} + HP_AUT_R2048 : HpAutR2048
            {static} + HP_ENC_R2048 : HpEncR2048
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.esign {
        class cardfilesystem.hba2mf.df.esign.PrK.HpAutR2048 {
            {static} + KID : int
        }
      }
    }
  }
  

  namespace cardfilesystem {
    namespace hba2mf {
      namespace df.esign {
        class cardfilesystem.hba2mf.df.esign.PrK.HpEncR2048 {
            {static} + KID : int
        }
      }
    }
  }
  

  cardfilesystem.hba2mf.df.esign.Ef +-down- cardfilesystem.hba2mf.df.esign.Ef.ChpAutR2048
  cardfilesystem.hba2mf.df.esign.Ef +-down- cardfilesystem.hba2mf.df.esign.Ef.ChpEncR2048
  cardfilesystem.hba2mf.df.esign.PrK +-down- cardfilesystem.hba2mf.df.esign.PrK.HpAutR2048
  cardfilesystem.hba2mf.df.esign.PrK +-down- cardfilesystem.hba2mf.df.esign.PrK.HpEncR2048


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
